# Generated by Django 5.2.3 on 2025-11-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLOYEE', 'Empleado'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10, verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
