# Generated by Django 5.2.3 on 2025-11-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INVESTIGADOR', 'Investigador')], default='INVESTIGADOR', max_length=15, verbose_name='Rol del Usuario'),
        ),
    ]
