# Generated by Django 5.0.2 on 2025-06-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
        ('convocatoria', '0001_initial'),
        ('empresa', '0001_initial'),
        ('investigador', '0001_initial'),
        ('lineainvestigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('claveInterna', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombreProyecto', models.CharField(error_messages={'blank': 'El nombre del proyecto es obligatorio.', 'max_length': 'El nombre del proyecto no puede exceder 90 caracteres.'}, max_length=90)),
                ('objetivos', models.TextField(error_messages={'blank': 'Los objetivos del proyecto son obligatorios.'})),
                ('resumen', models.TextField(error_messages={'blank': 'El resumen del proyecto es obligatorio.'})),
                ('fechaInicio', models.DateField(error_messages={'blank': 'La fecha de inicio es obligatoria.'})),
                ('fechaFin', models.DateField(error_messages={'blank': 'La fecha de fin es obligatoria.'})),
                ('financiamiento', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=None, max_length=2, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vinculado', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=None, max_length=2, null=True)),
                ('colaboradorProyecto', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('areaDesarrolloTec', models.CharField(error_messages={'max_length': 'El área de desarrollo tecnológico no puede exceder 45 caracteres.'}, max_length=45)),
                ('desarrolloTecnologico', models.BooleanField(blank=True, default=None, null=True)),
                ('estatusProyecto', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=None, max_length=8, null=True)),
                ('claveCarrera', models.ForeignKey(blank=True, db_column='claveCarrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
                ('clave_convocatoria', models.ForeignKey(db_column='clave_convocatoria', on_delete=django.db.models.deletion.CASCADE, to='convocatoria.convocatoria')),
                ('liderProyecto', models.ForeignKey(blank=True, db_column='liderProyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='investigador.investigador')),
                ('lineaInvestigacion_LineaPk', models.ForeignKey(db_column='lineaInvestigacion_LineaPk', on_delete=django.db.models.deletion.CASCADE, to='lineainvestigacion.lineainvestigacion')),
                ('rfc_Empresa', models.ForeignKey(db_column='rfc_Empresa', on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
