# Generated by Django 5.2.3 on 2025-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='claveInterna',
            field=models.CharField(blank=True, editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
