# Generated by Django 5.2.3 on 2025-06-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_remove_metas_proyecto'),
        ('proyecto', '0002_alter_proyecto_claveinterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='metas',
            field=models.ManyToManyField(related_name='proyectos', to='metas.metas'),
        ),
    ]
