# Generated by Django 5.2.3 on 2025-06-24 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_remove_metas_proyecto'),
        ('proyecto', '0003_proyecto_metas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='metas',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipoProyecto',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Continuidad', 'Continuidad')], default=None, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='MetaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metas.metas')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
    ]
