# Generated by Django 5.2.3 on 2025-06-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_remove_metas_proyecto'),
        ('proyecto', '0004_remove_proyecto_metas_proyecto_tipoproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='metas',
            field=models.ManyToManyField(related_name='proyectos', through='proyecto.MetaProyecto', to='metas.metas'),
        ),
    ]
