# Generated by Django 5.0.2 on 2025-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('idLineaInvestigacion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(error_messages={'blank': 'El nombre es obligatorio.', 'max_length': 'El nombre no puede exceder 300 caracteres.'}, max_length=300)),
                ('institucionRegistro', models.CharField(blank=True, default=None, error_messages={'max_length': 'La institución de registro no puede exceder 100 caracteres.'}, max_length=100, null=True)),
            ],
        ),
    ]
