# Generated by Django 5.2.3 on 2025-06-24 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_alter_carrera_clavecarrera'),
        ('lineainvestigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='claveCarrera',
            field=models.ForeignKey(blank=True, db_column='claveCarrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera'),
        ),
    ]
