# Generated by Django 5.0.2 on 2025-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('claveCarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=120)),
            ],
        ),
    ]
