# Generated by Django 5.2.3 on 2025-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='claveCarrera',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
