# Generated by Django 5.0.2 on 2025-06-11 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('clave_convocatoria', models.CharField(blank=True, error_messages={'blank': 'La clave de la convocatoria es obligatoria.', 'max_length': 'La clave de la convocatoria no puede exceder 13 caracteres.'}, max_length=13, primary_key=True, serialize=False)),
                ('convocatoria', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='El formato del nombre de la convocatoria no es válido', regex='^[\\w\\s\\.\\&\\-\\u00C0-\\u00FF]+$')])),
                ('fechaInicioFinanciamiento', models.DateField()),
                ('fechaFinFinanciamiento', models.DateField()),
                ('institucionFinanciamiento', models.CharField(blank=True, error_messages={'max_length': 'La institución de financiamiento no puede exceder 200 caracteres.'}, max_length=200, null=True)),
            ],
        ),
    ]
