# Generated by Django 5.2.3 on 2025-11-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/'),
        ),
    ]
