# Generated by Django 5.2.3 on 2025-11-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_convocatoria_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(blank=True, error_messages={'max_length': 'La descripción no puede exceder 500 caracteres.'}, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fechaFinConvocatoria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fechaInicioConvocatoria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'decimal_places': 'El presupuesto debe tener 2 decimales.', 'max_digits': 'El presupuesto no puede exceder 12 dígitos.'}, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='requisitos',
            field=models.TextField(blank=True, error_messages={'max_length': 'Los requisitos no pueden exceder 500 caracteres.'}, max_length=500, null=True),
        ),
    ]
