# Generated by Django 5.2.3 on 2025-11-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0003_convocatoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='activa',
            field=models.BooleanField(default=False, help_text='Indica si la convocatoria está activa. Solo puede ponerse True si la fecha actual está entre fechaInicioConvocatoria y fechaFinConvocatoria.'),
        ),
    ]
