# Generated by Django 5.0.2 on 2025-06-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
        ('credenciales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=90)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('claveCarrera', models.ForeignKey(db_column='claveCarrera', on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
                ('id_Credencial', models.ForeignKey(db_column='id_Credencial', on_delete=django.db.models.deletion.CASCADE, to='credenciales.credenciales')),
            ],
        ),
    ]
