# Generated by Django 5.0.2 on 2025-06-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigador', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('idcolaboradores', models.AutoField(primary_key=True, serialize=False)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to='investigador.investigador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='proyecto.proyecto')),
            ],
        ),
    ]
