# Generated by Django 5.0.2 on 2025-06-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('noControl', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=90)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('claveCarrera', models.ForeignKey(db_column='claveCarrera', on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
                ('claveProyecto', models.ForeignKey(blank=True, db_column='claveInterna', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
    ]
