# Generated by Django 5.2.3 on 2025-06-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
        ('proyecto', '0002_alter_proyecto_claveinterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='proyecto.proyecto'),
        ),
    ]
