# Generated by Django 5.2.3 on 2025-06-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_metas_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='proyecto',
        ),
    ]
