# Generated by Django 5.0.2 on 2025-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id_Credencial', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=256)),
                ('Rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Investigador', 'Investigador')], max_length=13)),
            ],
        ),
    ]
