# Generated by Django 5.2.3 on 2025-06-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credenciales',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='credenciales',
            name='usuario',
        ),
        migrations.AddField(
            model_name='credenciales',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to=settings.AUTH_USER_MODEL),
        ),
    ]
