# Generated by Django 5.0.2 on 2025-06-11 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El formato del RFC no es válido', regex='^[A-ZÑ&]{3,4}\\d{6}(?:[A-Z\\d]{2}[A\\d])?$')])),
                ('razonSocial', models.CharField(error_messages={'blank': 'La razón social es obligatoria.', 'max_length': 'La razón social no puede exceder 300 caracteres.'}, max_length=300)),
                ('sector', models.CharField(choices=[('Publico', 'Público'), ('Privado', 'Privado')], max_length=8)),
                ('tipoEmpresa', models.CharField(error_messages={'blank': 'El tipo de empresa es obligatorio.', 'max_length': 'El tipo de empresa no puede exceder 100 caracteres.'}, max_length=100)),
            ],
        ),
    ]
